//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ishbaev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ishbaevEntities : DbContext
    {
        public ishbaevEntities()
            : base("name=ishbaevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Бухгалтерия> Бухгалтерия { get; set; }
        public virtual DbSet<Приёмка> Приёмка { get; set; }
        public virtual DbSet<Разгрузка> Разгрузка { get; set; }
        public virtual DbSet<СоставПриёмки> СоставПриёмки { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
