//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ishbaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бухгалтерия
    {
        public int ID_операции { get; set; }
        public int ID_приёмки { get; set; }
        public System.DateTime Дата_операции { get; set; }
        public string Тип_операции { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Бухгалтер { get; set; }
        public string Утвердил_менеджер { get; set; }
        public Nullable<int> ID_товара { get; set; }
    
        public virtual Приёмка Приёмка { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
