//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ishbaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приёмка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Приёмка()
        {
            this.Бухгалтерия = new HashSet<Бухгалтерия>();
            this.Разгрузка = new HashSet<Разгрузка>();
            this.СоставПриёмки = new HashSet<СоставПриёмки>();
        }
    
        public int ID_приёмки { get; set; }
        public System.DateTime Дата { get; set; }
        public string Поставщик { get; set; }
        public decimal Количество { get; set; }
        public decimal Закупочная_цена { get; set; }
        public string Ответственный_менеджер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бухгалтерия> Бухгалтерия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Разгрузка> Разгрузка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПриёмки> СоставПриёмки { get; set; }
    }
}
