//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ishbaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разгрузка
    {
        public int ID_разгрузки { get; set; }
        public int ID_приёмки { get; set; }
        public System.DateTime Дата_разгрузки { get; set; }
        public string Транспорт { get; set; }
        public string Водитель { get; set; }
        public string Грузчик { get; set; }
        public string Примечание { get; set; }
        public Nullable<int> ID_товара { get; set; }
    
        public virtual Приёмка Приёмка { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
