//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ishbaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставПриёмки
    {
        public int ID_записи { get; set; }
        public int ID_приёмки { get; set; }
        public int ID_товара { get; set; }
        public decimal Количество { get; set; }
        public decimal Закупочная_цена { get; set; }
    
        public virtual Приёмка Приёмка { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
